window.__t = {
	error_invalid_email: "Введенный Электронный адрес некорректен!",
	error_user_exists: "Пользователь с такими данными уже есть!",
	to_select: "выбрать",
	select: "выбор",
	street: "улица",
	house: "дом",
	year: "год",
	month: "месяц",
	vid_sobstv: "вид собственности",
	saldo_start: "остаток на начало",
	nachisleno: "Начислено",
	pereraschet: "Перерасчеты",
	oplacheno: "Оплачено",
	saldo_end: "Остаток на конец",
	soderganie: "содержание",
	elen: "эл\эн",
	vsego: "всего",
	itogo: "итого",
	preview: "предпросмотр",
	fio: "Фамилия имя отчество",
	login: "логин",
	name: "имя",
	password: "пароль",
	email: "Эл.почта",
	phone: "телефон",
	passport: "паспорт",
	dob: "дата рождения",
	adres: "адрес",
	seriya: "серия",
	number: "номер",
	addres: "адрес",
	regflat: "адрес регистрации",
	organization: "организация",
	error_not_found_name_module: 'Не найден название модуля',
	error_dir_is_exists: 'Такая папка существует',
	created: 'создано',
	create: 'создать',
	to_create: 'создать',
	module: 'модуль',
	dir: 'папка',
	link: 'ссылка',
	title: 'название',
	path: 'путь',
	error_not_found_lc: 'Ненайден лицевой счет!',
	enter_lc: 'Введите лицевой счет!',
	success_payment: 'Оплата успешна произведена!',
	failed_payment: 'Оплата НЕ произведена!',
	e_house: 'Надо выбрать номер дома!',
	error_enter_house: 'Надо выбрать номер дома!',
	e_period: "Надо выбрать период!",
	error_enter_period: "Надо выбрать период!",
	only_delete_users: 'Только поставленные на удаление',
	dulis: 'Лицевой счёт',
	lc: 'Лицевой счёт',
	ip: "IP",
	country: "страна",
	city: "город",
	not_updated: "Не обновлено!",
	updated: "Обновлено!",
	not_save: "Не сохранено!",
	save: "Сохранено!",
	saved: "Сохранено!",
	add: "Добавлено",
	not_add: "Не добавлено!",
	btn_save: "Сохранить",
	to_save: "Сохранить",
	btn_add: "Добавить",
	to_add: "Добавить",
	deleted: "Удалено",
	to_delete: "Удалить",
	not_deleted: "Не удалено",
	msg_not_deleted: "Не удалено",
	q_delete: "Удалить?",
	q_save: "Сохранить?",
	q_add: "Добавить?",
	q_set_active: "Разблокировать пользователя.",
	q_un_set_active: "Заблокировать пользователя?",
	q_set_delete: "Поставить на удаление?",
	q_un_set_delete: "Снять с удаления?",
	q_update_password: "Изменить пароль?",
	q_send_reg_to_email: "Послать на электронную почту?",
	e_valid_email: "Ошибка в электронном адресе!",
	manager_news: "Управление новостями",
	caption: "заголовок",
	published: "опубликован",
	not_published: "не опубликован",
	yes: "да",
	no: "нет",
	date: "дата",
	to_public: "Опубликовать",
	publiched: "Опубликован",
	date_public: "дата публикации",
	description: "описание",
	e_login: "Неправильно введен логин или пароль!",
	vid_sch: "Вид счетчика",
	mesto_sch: "Место установки",
	date_och_pov: "Дата очередной поверки",
	ser_sch: "Серийный номер",
	serial_number: "Серийный номер",
	prev_pokazanie: "Предыдущие показания",
	tek_pokazanie: "Текущие показания",
	number_house: "номер дома",
	enter_number_house: "номер дома",
	number_korpus: "номер корпуса",
	enter_number_korpus: "номер корпуса",
	number_flat: "номер квартиры",
	enter_number_flat: "Введите номер квартиры",
	search: "Поиск",
	search_from_dulis: "Поиск по лицевому счету",
	msg_enter_control_value: "Для избежания ошибки заполните контрольные значения",
	q_value_dulis: "Как узнать свой лицевой счет?",
	new_search: "Новый поиск",
	reset: "Сброс",
	enter_dulis: "Введите номер вашего лицевого счета",
	msg_all_counters: "если нет корпуса или квартиры, оставьте поля пустыми или введите 0",
	send: "Отправить",
	msg_accepted_condition: "Согласитесь с условиями договора",
	msg_accepted_payment: "Согласитесь с условиями оплаты.",
	e_save: "Ошибка сохранения",
	e_saved: "Ошибка сохранения",
	error_saved: "Ошибка сохранения",
	success_save: "Успешно сохранено",
	e_captcha: "Неверно введен проверочный код",
	value_not_found: "Значение не найдено"
};